"""Rendering: a rich console report for humans, markdown for CI summaries."""

from __future__ import annotations

from gauntlet.models import AttackResult, RunReport
from gauntlet.taxonomy import atlas_label, owasp_label


def _status(r: AttackResult) -> str:
    if r.error:
        return "ERROR"
    return "BREACHED" if r.breached else "withstood"


def render_console(report: RunReport, drift: dict) -> None:
    from rich.console import Console
    from rich.panel import Panel
    from rich.table import Table

    console = Console()
    table = Table(show_lines=False, expand=True)
    table.add_column("Scenario", style="bold")
    table.add_column("Sev")
    table.add_column("OWASP")
    table.add_column("Result")
    table.add_column("Evidence", overflow="fold")

    for r in report.results:
        result_txt = _status(r)
        if r.error:
            style = "yellow"
            evidence = r.error
        elif r.breached:
            style = "red"
            evidence = r.evidence
        else:
            style = "green"
            evidence = r.evidence
        owasp = ", ".join(r.taxonomy.owasp) or "-"
        table.add_row(
            r.title,
            r.severity.value.upper(),
            owasp,
            f"[{style}]{result_txt}[/{style}]",
            evidence,
        )

    console.print(table)

    verdict = "[green bold]PASS[/green bold]" if report.passed else "[red bold]FAIL[/red bold]"
    lines = [
        f"Target: {report.target_name}",
        f"Resilience score: [bold]{report.resilience_score}[/bold] / 100   (threshold {report.threshold})",
        f"Breaches: {len(report.breaches)}/{report.total}   Errors: {len(report.errored)}",
        f"Gate: {verdict}",
    ]
    if drift.get("delta") is not None:
        arrow = "up" if drift["delta"] > 0 else ("down" if drift["delta"] < 0 else "flat")
        lines.append(f"Drift vs last run: {arrow} {drift['delta']:+} (was {drift['previous_score']})")
        if drift["regressions"]:
            lines.append(f"[red]New regressions: {', '.join(drift['regressions'])}[/red]")
        if drift["fixes"]:
            lines.append(f"[green]Newly resilient: {', '.join(drift['fixes'])}[/green]")
    console.print(Panel("\n".join(lines), title="Gauntlet", border_style="green" if report.passed else "red"))


def render_markdown(report: RunReport, drift: dict) -> str:
    verdict = "✅ **PASS**" if report.passed else "❌ **FAIL**"
    out: list[str] = []
    out.append("# 🛡️ Gauntlet — Agentic Red-Team Gate")
    out.append("")
    out.append(f"**Target:** `{report.target_name}`  ")
    out.append(
        f"**Resilience score:** {report.resilience_score}/100 "
        f"(threshold {report.threshold}) — {verdict}  "
    )
    out.append(f"**Breaches:** {len(report.breaches)}/{report.total} · **Errors:** {len(report.errored)}")
    if drift.get("delta") is not None:
        out.append(f"**Drift vs last run:** {drift['delta']:+} (was {drift['previous_score']})")
        if drift["regressions"]:
            out.append(f"> ⚠️ New regressions: {', '.join(drift['regressions'])}")
        if drift["fixes"]:
            out.append(f"> ✅ Newly resilient: {', '.join(drift['fixes'])}")
    out.append("")
    out.append("| Scenario | Severity | OWASP | MITRE ATLAS | Result | Evidence |")
    out.append("|---|---|---|---|---|---|")
    for r in report.results:
        owasp = "<br>".join(owasp_label(c) for c in r.taxonomy.owasp) or "-"
        atlas = "<br>".join(atlas_label(c) for c in r.taxonomy.atlas) or "-"
        mark = "🟡 error" if r.error else ("🔴 BREACHED" if r.breached else "🟢 withstood")
        evidence = (r.error or r.evidence).replace("|", "\\|")
        out.append(f"| {r.title} | {r.severity.value.upper()} | {owasp} | {atlas} | {mark} | {evidence} |")
    out.append("")
    out.append("<sub>Generated by Gauntlet — continuous agentic red-teaming.</sub>")
    return "\n".join(out)
